### ISSUE TITLE
correlation between the allele frequencies in A1A0 and B1B0

### ISSUE THREAD

**Issue by nenduru1** [wouterpeyrot/CCGWAS#12]
Hi,

the suggested correlation criteria between the allele frequencies do not meet the requirement. what does this suggest?
does this affect the outcome?

Of these overlapping SNPs... (this overview can help to double-check input)
...the mean OR in A1A0 equals 1.00089 (should be very close to 1)
...the mean OR in B1B0 equals 1.00042 (should be very close to 1)
...55 are signifacntly associated with A1A0 at p<5e-8
...1,097 are signifacntly associated with B1B0 at p<5e-8
...the mean allele frequency in A1A0 equals 0.27274
...the mean allele frequency in B1B0 equals 0.45701
...the correlation between the allele frequencies in A1A0 and B1B0 is **0.06714 (should be very close to 1, i.e. > 0.98)**

thank you.

**Comment by wouterpeyrot** [comment]
Given the mean allele frequency in A1A0, could it be the A1A0 sumstats include the minor allele frequency instead of the effective allele frequency? This would explain the low correlation. Most important is that the effective allele is coded 100% correctly. If so, you can safely proceed. (If the effective allele is not coded correctly, you risk severely inflate type I error rate.)
