### ISSUE TITLE
...CC-GWAS is being aborted, because mean(beta_viaNeff/beta_viaOR) = 1.3499 > 1.1 risking inflated type I error at stress test SNPs. Please contact wpeyrot@hsph.harvard.edu to resolve this issue.

### ISSUE THREAD

**Issue by HongyanR** [wouterpeyrot/CCGWAS#2]
Hi, I ran into this issue when trying to use the programme, any suggestion would be much appreciated. Thanks!

**Comment by wouterpeyrot** [comment]
Some GWAS results present half N_eff (if this is the case you need to multiply Neff by 2). Can you check if this is the case? Thanks, Wouter

**Comment by Xuemin-Wang** [comment]
Hi Wouter,

I have the N column (N = N_case + N_control), but encountered the same issue indicating "mean(beta_viaNeff/beta_viaOR) = 0.6357 < 0.9". So I calculated Neff = 4 / (1/N_case + 1/N_control)) but the same issue was raised (mean(beta_viaNeff/beta_viaOR) = 0.868 < 0.9). Then I calculated Neff using Neff = 1 / (2*FRQ*(1-FRQ)*SE^2), but had "mean(beta_viaNeff/beta_viaOR) = 2.0002 > 1.1" this time. 

I noticed that "50 SNPs were deleted based on OR>2 or OR<0.5". Could this cause the issue? Can you think of any other solutions to fix this issue?

Many thanks,
xuemin

**Comment by Xuemin-Wang** [comment]
Just tried filtering out variants with imputation quality < 0.8, mean(beta_viaNeff/beta_viaOR) = 0.8872 but still < 0.9. "17 SNPs were deleted based on OR>2 or OR<0.5 ".

I further tried filtering out variants with imputation quality < 0.9, mean(beta_viaNeff/beta_viaOR) = 0.8961 but still < 0.9. "9 SNPs were deleted based on OR>2 or OR<0.5 ".

Regards,
xuemin

**Comment by wouterpeyrot** [comment]
Hi Xuemin,
Please try to use Neff = (0.868^2) * 4 / (1/N_case + 1/N_control)). 
Let me know if this works.
Best Wouter

**Comment by Xuemin-Wang** [comment]
Hi Wouter,

Thanks very much for your reply.

Neff calculation as suggested did make CCGWAS work. May I ask why including the 0.868^2 term into the Neff calculation? 

If allele frequencies of controls in both case/control studies are the same (e.g. two subtypes of a cancer), will CC-GWAS unlikely to detect any significantly associated variant? I guess it will since CC-GWAS relies on differences in effect allele frequencies in both case/control studies.

Many thanks,
xuemin

**Comment by came203** [comment]
Hi Wouter,

I have the same problem with multiple published GWAS I used. Mean(beta_viaNeff/beta_viaOR) is always the culprit, the solution you offered above doesn't help in every case.

Best
Rainer

**Comment by wouterpeyrot** [comment]
Hi Xuemin and Rainer,

CC-GWAS transforms the beta to the standardized observed scale in two ways. Computing mean(beta_viaNeff/beta_viaOR) double-checks if these two approaches align. By multiplying Neff with mean(beta_viaNeff/beta_viaOR)^2 you are bypassing this double-check. For more details, also see Supplements bottom page 26 and top page 27. 

When using this bypass, make sure the OR’s in the case-control GWAS are correct, i.e. the OR for disease per additional effective allele. Also make sure that CC-GWAS is intended for within ancestry analyses (otherwise differences in population allele frequencies and LD patterns can lead to false positive case-case associations).

@Xuemin, 0.868 is the value you gave for mean(beta_viaNeff/beta_viaOR) in one of your previous messages.

Hope this helps.

Best Wouter

**Comment by came203** [comment]
Hi Wouter, 

thanks for the explanation, that makes sense. 

Best wishes
Rainer

**Comment by Xuemin-Wang** [comment]
Hi Wouter,

Thanks for your info.

When applying your method to two histological subtypes of a disease (one common and the other rare), if the same EAF of controls in both subtypes are used, will CC-GWAS unlikely to find additional significant associations?

Cheers,
xuemin

**Comment by wouterpeyrot** [comment]
Hi Xuemin,

When comparing subtypes, make sure to set "subtype_data=TRUE" in CC-GWAS. The resulting power depends on the sample-size you have for both subtypes. If one subtype is very rare, then you expect little power. Did you specify the number of overlapping controls? This can help to increase power (slightly).

Hope this helps. 

Best Wouter

**Comment by Xuemin-Wang** [comment]
Hi Wouter,

Thanks for your info. 

I set subtype_data=TRUE and specified the number of overlapping controls. Results were similar to subtype case-case analysis, identifying no significant association. However, there were quite a few variants having p.OLS<5e-8, but they were filtered due to p.Exact>1e-4. I agree that this is again due to the under-powered GWAS of the rare subtype caused by its small sample size.

Brilliant method though. 

Cheers,
xuemin

**Comment by wouterpeyrot** [comment]
Do I understand correctly you also have a direct case-case comparison? Did you consider running CC-GWAS+? CC-GWAS+ also uses the direct case-case comparison to increase power. Best wishes Wouter

**Comment by rcliffo6** [comment]
I seem to have the opposite problem now. When I use some public summary statistics for B1B0, I receive the error,
mean(beta_viaNeff/beta_viaOR) = 4.4488 > 1.1 on the set. Why would this be? I can correct it with the 4.4488^2*Neff, but how can I correct this in the statistics themselves. I have used INFO > .80, MAF > .01, and there are sufficient cases and controls - 87,056 cases and 163,333 controls, with no overlap between A1A0 and B1B0. 
A1A0 (my data) is computing well, but B1B0 is not. Thanks for any insight anyone would have.

**Comment by wouterpeyrot** [comment]
Can you give me the summary of the Neff values in the input data in B1B0?

**Comment by rcliffo6** [comment]
These are summary statistics from 2 papers that did meta-analysis on 4 European populations, Iceland, Finland, US, and UKB, each done with PLINK then meta-analysis via METAL. The first is on balance, with the 4.4488 > 1.1. N-cases = 48,072, N-controls = 894,541. Since I do not have numbers on individual SNPs, I used the formula 4/{(1/N-cases) + (1/N-controls)} and came up with 182481.6 .

The second is on hearing difficulties, solely on UKB data (not a meta-analysis), and I received the note that 1.8 > 1.1 Here N-cases = 87,056 and N-controls = 163,333 and came up with 227152.
I used the correction on both of these (the second was quite close), but I'm concerned about inflation in my results. Thanks for looking at these - if you want the sumstats or any other information, I can send them.

**Comment by wouterpeyrot** [comment]
Sorry for my delay in getting back to you. 

For "4.4488 > 1.1", can you also compute the sum of Neff? That is, compute the Neff per contributing cohort, and than add all Neffs. This will highly likely yield a much smaller Neff. Also see Grotzinger et al. 2022 Biol Psychiatry.

For "1.8 > 1.1", this is surprising given it is not a meta-analyses. At some point I change the double check from mean() to median(). Could you reload CCGWAS and try again? Did you run the hearing GWAS yourself? If not, you could also consider contacting the respective authors to double-check N.

**Comment by rcliffo6** [comment]
Hi!
Thanks for getting back to me. I gave up on
B1B0 was a meta-analysis. I did CCGWAS with the smaller Neff and it worked. I got one hit that was significantly different (10e-27!). The B1B0 was not done by me, just the A1A0 – on balance. I used 1.0. Is there a newer version?
It will be in my paper that I’m just submitting, and I will acknowledge you for your help.
Royce


From: Wouter Peyrot ***@***.***>
Reply-To: wouterpeyrot/CCGWAS ***@***.***>
Date: Friday, October 21, 2022 at 6:47 AM
To: wouterpeyrot/CCGWAS ***@***.***>
Cc: brendan clifford ***@***.***>, Comment ***@***.***>
Subject: Re: [wouterpeyrot/CCGWAS] ...CC-GWAS is being aborted, because mean(beta_viaNeff/beta_viaOR) = 1.3499 > 1.1 risking inflated type I error at stress test SNPs. Please contact ***@***.*** to resolve this issue. (#2)


Sorry for my delay in getting back to you.

For "4.4488 > 1.1", can you also compute the sum of Neff? That is, compute the Neff per contributing cohort, and than add all Neffs. This will highly likely yield a much smaller Neff. Also see Grotzinger et al. 2022 Biol Psychiatry.

For "1.8 > 1.1", this is surprising given it is not a meta-analyses. At some point I change the double check from mean() to median(). Could you reload CCGWAS and try again? Did you run the hearing GWAS yourself? If not, you could also consider contacting the respective authors to double-check N.

**Comment by rcliffo6** [comment]
I checked - since I have an older Mac, it uses an older version of R, and I have CCGWAS version 1.0. Is there a way to change the mean() to median()? on that one?

**Comment by wouterpeyrot** [comment]
I have updated it on github, so you can simply update it by rerunning `install_github("wouterpeyrot/CCGWAS")`
